# Generated by Django 3.2.16 on 2022-12-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
